; PlatformIO Project Configuration File
[platformio]
default_envs = esp32s3_zero

[common]
platform = espressif32
framework = espidf
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -std=gnu++20
    ; ESP-IDF sdkconfig options
    -DSDKCONFIG_DEFAULTS=${PROJECT_DIR}/sdkconfig.defaults

build_unflags =
    -std=gnu++11

[env:esp32s3_zero]
extends = common
board = esp32-s3-devkitm-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = partitions.csv
build_flags =
    ${common.build_flags}
    -DUSER_LED_PIN=GPIO_NUM_21

[env:esp32s3_zero_dev]
extends = env:esp32s3_zero
build_type = debug
build_flags =
    ${env:esp32s3_zero.build_flags}
    -DDEV_LOGS=1
